# Generated by Django 6.0.5 on 2026-05-18 12:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_workerprofile_current_latitude_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementRequest',
            fields=[
                ('settlement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='settlement_proofs/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.unionprofile')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_requests', to='accounts.workerprofile')),
            ],
        ),
    ]
