# Generated by Django 6.0.5 on 2026-05-12 09:31

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('CUSTOMER', 'Customer'), ('WORKER', 'Worker'), ('UNION_ADMIN', 'Union Admin'), ('SUPER_ADMIN', 'Super Admin')], max_length=30)),
                ('language', models.CharField(choices=[('en', 'English'), ('ml', 'Malayalam')], default='en', max_length=10)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(default='Kerala', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_type', models.CharField(blank=True, choices=[('textile', 'Textile Shop'), ('wholesale', 'Wholesale Market'), ('vegetable', 'Vegetable Market'), ('hardware', 'Hardware'), ('construction', 'Construction'), ('household', 'Household'), ('other', 'Other')], max_length=50, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('hybrid', 'Hybrid')], default='cash', max_length=20)),
                ('total_completed_works', models.PositiveIntegerField(default=0)),
                ('total_amount_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dispute_count', models.PositiveIntegerField(default=0)),
                ('customer_rating', models.FloatField(default=5.0)),
                ('saved_addresses', models.JSONField(blank=True, default=list)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=10)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('password_reset', 'Password Reset')], max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('union_name', models.CharField(max_length=255)),
                ('union_code', models.CharField(max_length=50, unique=True)),
                ('operational_area', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('union_address', models.TextField()),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='union_documents/')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_workers', models.PositiveIntegerField(default=0)),
                ('total_completed_works', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('active_workers', models.PositiveIntegerField(default=0)),
                ('dispute_cases', models.PositiveIntegerField(default=0)),
                ('operational_radius_km', models.PositiveIntegerField(default=10)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_active_union', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='union_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=50, unique=True)),
                ('aadhaar_number', models.CharField(max_length=20, unique=True)),
                ('aadhaar_document', models.FileField(blank=True, null=True, upload_to='worker_documents/')),
                ('emergency_contact', models.CharField(max_length=20)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('workload_score', models.FloatField(default=0)),
                ('total_completed_works', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('today_work_count', models.PositiveIntegerField(default=0)),
                ('weekly_work_count', models.PositiveIntegerField(default=0)),
                ('idle_time_hours', models.PositiveIntegerField(default=0)),
                ('average_rating', models.FloatField(default=5.0)),
                ('dispute_count', models.PositiveIntegerField(default=0)),
                ('reliability_score', models.FloatField(default=100)),
                ('last_work_completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_team_lead_eligible', models.BooleanField(default=False)),
                ('is_currently_assigned', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('joined_union_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('union', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='accounts.unionprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
