# Generated by Django 6.0.5 on 2026-05-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unionprofile',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unionprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unionprofile',
            name='operational_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unionprofile',
            name='union_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unionprofile',
            name='union_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='unionprofile',
            name='union_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
