# Generated by Django 6.0.5 on 2026-05-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_unionprofile_latitude_unionprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='last_location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
