# Generated by Django 6.0.5 on 2026-05-13 09:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_customerprofile_is_profile_completed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireTemplate',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_type', models.CharField(choices=[('shop_unloading', 'Shop Unloading'), ('market_loading', 'Market Loading'), ('household_shifting', 'Household Shifting'), ('construction', 'Construction'), ('warehouse', 'Warehouse'), ('other', 'Other')], max_length=100)),
                ('question', models.CharField(max_length=500)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('boolean', 'Boolean')], max_length=50)),
                ('options', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('work_type', models.CharField(choices=[('shop_unloading', 'Shop Unloading'), ('market_loading', 'Market Loading'), ('household_shifting', 'Household Shifting'), ('construction', 'Construction'), ('warehouse', 'Warehouse'), ('other', 'Other')], max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('questionnaire_answers', models.JSONField(blank=True, default=dict)),
                ('interpreted_requirements', models.JSONField(blank=True, default=dict)),
                ('goods_details', models.JSONField(blank=True, default=dict)),
                ('estimated_workers', models.PositiveIntegerField(default=1)),
                ('estimated_duration_hours', models.FloatField(default=1)),
                ('estimated_weight_kg', models.FloatField(default=0)),
                ('estimated_distance_meters', models.FloatField(default=0)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('difficulty_score', models.FloatField(default=0)),
                ('work_address', models.TextField()),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('work_start_time', models.DateTimeField(blank=True, null=True)),
                ('work_completed_time', models.DateTimeField(blank=True, null=True)),
                ('suggested_team_generated', models.BooleanField(default=False)),
                ('system_confidence_score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('union_review', 'Union Review'), ('team_suggested', 'Team Suggested'), ('team_confirmed', 'Team Confirmed'), ('workers_notified', 'Workers Notified'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completion_pending', 'Completion Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', max_length=50)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_union', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='accounts.unionprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_requests', to='accounts.customerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkEvidence',
            fields=[
                ('evidence_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('arrival', 'Arrival'), ('start', 'Start'), ('completion', 'Completion'), ('damage', 'Damage'), ('dispute', 'Dispute')], max_length=50)),
                ('image', models.ImageField(upload_to='work_evidences/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='work_requests.workrequest')),
            ],
        ),
        migrations.CreateModel(
            name='WorkAssignment',
            fields=[
                ('assignment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='assigned', max_length=30)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.unionprofile')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_assignments', to='accounts.workerprofile')),
                ('work_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_assignments', to='work_requests.workrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('dispute_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
                ('work_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='work_requests.workrequest')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedTeam',
            fields=[
                ('team_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_workers', models.PositiveIntegerField(default=0)),
                ('preference_match_score', models.FloatField(default=0)),
                ('workload_balance_score', models.FloatField(default=0)),
                ('system_generated', models.BooleanField(default=True)),
                ('union_modified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('completed', 'Completed')], default='suggested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by_union', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teams', to='accounts.unionprofile')),
                ('team_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_teams', to='accounts.workerprofile')),
                ('workers', models.ManyToManyField(related_name='assigned_teams', to='accounts.workerprofile')),
                ('work_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_team', to='work_requests.workrequest')),
            ],
        ),
        migrations.CreateModel(
            name='WorkStatusLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('team_generated', 'Team Generated'), ('workers_assigned', 'Workers Assigned'), ('workers_arrived', 'Workers Arrived'), ('work_started', 'Work Started'), ('completion_requested', 'Completion Requested'), ('completed', 'Completed'), ('disputed', 'Disputed')], max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='work_requests.workrequest')),
            ],
        ),
    ]
