# Generated by Django 6.0.5 on 2026-05-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workassignment',
            name='is_team_leader',
            field=models.BooleanField(default=False),
        ),
    ]
