# Generated by Django 6.0.5 on 2026-05-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_requests', '0002_workassignment_is_team_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('union_review', 'Union Review'), ('team_suggested', 'Team Suggested'), ('team_confirmed', 'Team Confirmed'), ('workers_notified', 'Workers Notified'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('workers_on_the_way', 'Workers On The Way'), ('workers_arrived', 'Workers Arrived'), ('completion_pending', 'Completion Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', max_length=50),
        ),
    ]
