# Generated by Django 6.0.5 on 2026-05-14 10:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_workerprofile_current_latitude_and_more'),
        ('work_requests', '0003_alter_workrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('union_review', 'Union Review'), ('team_suggested', 'Team Suggested'), ('team_confirmed', 'Team Confirmed'), ('workers_notified', 'Workers Notified'), ('accepted', 'Accepted'), ('workers_on_the_way', 'Workers On The Way'), ('workers_arrived', 'Workers Arrived'), ('in_progress', 'In Progress'), ('completion_pending', 'Completion Pending'), ('payment_pending', 'Payment Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('customer_payment_confirmed', models.BooleanField(default=False)),
                ('worker_payment_confirmed', models.BooleanField(default=False)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_signature', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customerprofile')),
                ('work_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='work_requests.workrequest')),
            ],
        ),
    ]
