# Generated by Django 6.0.5 on 2026-05-17 14:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_workerprofile_current_latitude_and_more'),
        ('work_requests', '0004_alter_workrequest_status_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='accounts.customerprofile')),
                ('work_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reviews', to='work_requests.workrequest')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.workerprofile')),
            ],
            options={
                'unique_together': {('work_request', 'worker', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='WorkerReview',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customerprofile')),
                ('work_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_reviews', to='work_requests.workrequest')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='accounts.workerprofile')),
            ],
            options={
                'unique_together': {('work_request', 'customer', 'worker')},
            },
        ),
    ]
