# Generated by Django 6.0.5 on 2026-05-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_requests', '0005_customerreview_workerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='earnings_distributed',
            field=models.BooleanField(default=False),
        ),
    ]
